# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "Home"
#  url = "#about"
#  weight = 10

[[main]]
  name = "About"
  url = "/bio/"
  weight = 20

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 30

[[main]]
  name = "Reading List"
  #url = "#featured"
  weight = 40
  identifier = "Reading List"
  
[[main]]
  name = "2019"
  url = "post/reading-list/2019"
  parent = "Reading List"
  
[[main]]
  name = "2018"
  url = "post/reading-list/2018"
  parent = "Reading List"
  
[[main]]
  name = "2017"
  url = "post/reading-list/2017"
  parent = "Reading List"

#[[main]]
#  name = "Tags"
#  url = "#tags"
#  weight = 50

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
