---
title: "2018 Reading List"
author: ~
date: '2018-01-30'
slug: reading-list/2018
categories: ["Books", "Reading List"]
tags: ["2018", "Reading List", "Read Harder"]
---

1. The Three-Body Problem by Cixin Liu, trans. by Ken Liu
2. Shoe Dog: A Memoir by the Creator of Nike by Phil Knight
3. Killers of the Flower Moon: The Osage Murders and the Birth of the FBI by David Grann
4. Gnomon by Nick Harkaway
5. The Ocean at the End of the Lane by Neil Gaiman
6. The Catcher in the Rye by J.D. Salinger
7. Siddhartha by Herman Hesse  
8. The Ministry of Utmost Happiness by Arundhati Roy  
9. Broken Angels by Richard K. Morgan  
10. The Political Campaign Desk Reference by Michael McNamara  
11. "Surely You're Joking, Mr. Feynman!" by Richard Feynman  
12. The Fifth Season by N.K. Jemisin  
13. The Obelisk Gate by N.K. Jemisin  
14. The Stone Sky by N.K. Jemisin  
15. White Noise by Don DeLillo  
16. Yes We (Still) Can: Politics In the Age of Obama, Twitter, and Trump by Dan Pfeiffer  
17. The Secret History by Donna Tartt  
18. A Gentleman in Moscow by Amor Towles  
19. Afterparty by Daryl Gregory  
20. Death by Meeting by Patrick Lencioni  
21. Winners Take All: The Elite Charade of Changing the World by Anand Giridharadas  
22. [The Color of Law: A Forgotten History of How Our Government Segregated America](https://tsteggall.github.io/post/color-of-law/) by Richard Rothstein  
23. Stubborn Attachments by Tyler Cowen  
24. Black Panther: A Nation Under Our Feet Book 1 by Ta-Nehisi Coates  
25. Open: An Autobiography by Andre Agassi
26. The Hard Thing About Hard Things: Building a Business When There Are No Easy Answers by Ben Horowitz  
27. Bad Blood: Secrets & Lies in a Silicon Valley Startup by John Carreyrou

